# The purpose of this pipeline is to exercise local developer workflow in the consolidated
# runtime repo. In particular, it is supposed to run the root "build" script just like any
# normal developer normally would and monitor regressions w.r.t. this fundamental scenario.

trigger: none

pr:
  branches:
    include:
    - main
    - release/*.*
  paths:
    exclude:
    - '*'

jobs:
#
# Build with Release config and Debug runtimeConfiguration
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: release
    platforms:
    - windows_x86
    - OSX_x64
    jobParameters:
      testGroup: innerloop
      nameSuffix: Runtime_Debug
      buildArgs: -c release -runtimeConfiguration debug

#
# Build with Debug config and Release runtimeConfiguration
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: debug
    platforms:
    - Linux_x64
    jobParameters:
      testGroup: innerloop
      nameSuffix: Runtime_Release
      buildArgs: -c debug -runtimeConfiguration release

#
# Build with RuntimeFlavor only. This excercise code paths where only Configuration is
# specified. Catches cases where we depend on Configuration also being specified
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: debug
    platforms:
    - Linux_x64
    jobParameters:
      testGroup: innerloop
      nameSuffix: RuntimeFlavor_Mono
      buildArgs: /p:RuntimeFlavor=Mono

#
# Build Mono + Libraries. This excercises the code path where we build libraries without
# first building CoreCLR
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: debug
    platforms:
    - windows_x64
    jobParameters:
      testGroup: innerloop
      nameSuffix: Mono_Libraries
      buildArgs: -subset mono+libs /p:RuntimeFlavor=Mono

#
# SourceBuild Build
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: release
    platforms:
    - Linux_x64
    jobParameters:
      nameSuffix: SourceBuild
      buildArgs: /p:DotNetBuildFromSource=true
